kind: PersistentVolume
apiVersion: v1
metadata:
   name: mypv
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mypvdata


