kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: mydeploy1
  template:
    metadata:
      name: mytemplate
      labels:
        name: mydeploy1
    spec:
      containers:
        - name: c001
          image: httpd
          ports:
            - containerPort: 80
