kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeploy
spec:
  replicas: 2
  selector:
    matchLabels:
        name: mydeploynode
  template:
      metadata:
         name: mytemp
         labels:
           name: mydeploynode
      spec:
        containers:
          - name: c89
            image: httpd
            ports:
              - containerPort: 80
